backend:
  name: git-gateway
  # name: test-repo
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /assets/images

collections:
  - label: 'music'
    name: 'music'
    folder: 'content'
    create: true
    filter: { field: 'type', value: 'music' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
  - label: 'profile'
    name: 'profile'
    folder: 'content'
    create: true
    filter: { field: 'type', value: 'profile' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
  - label: 'travel'
    name: 'travel'
    folder: 'content'
    create: true
    filter: { field: 'type', value: 'travel' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
