backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images
public_folder: /images

collections:
  - label: 'music'
    name: 'music'
    folder: 'content/music'
    create: true
    filter: { field: 'type', value: 'music' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Preview', name: 'preview', widget: 'image' }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
  - label: 'profile'
    name: 'profile'
    folder: 'content/profile'
    create: true
    filter: { field: 'type', value: 'profile' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Preview', name: 'preview', widget: 'image' }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
  - label: 'daily'
    name: 'daily'
    folder: 'content/daily'
    create: true
    filter: { field: 'type', value: 'daily' }
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Preview', name: 'preview', widget: 'image' }
      - label: Images
        name: images
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
